# Generated by Django 4.1.7 on 2023-04-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
