# Generated by Django 4.1.7 on 2023-04-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
